# These settings are synced to GitHub by https://github.com/probot/settings
# Note that changes to this file will not automatically propogate to other repos that extend this file.
# The settings file in each of those repos will need to be `touched` to trigger an update.

repository:
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

labels:
  - name: bug
    color: fbca04
  - name: security
    color: ee0701
  - name: "help wanted"
    color: 008672
  - name: "good first issue"
    color: 7057ff

# Collaborators: give specific users access to this repository.
# collaborators:
#   - username: bkeepers
#     # Note: Only valid on organization-owned repositories.
#     # The permission to grant the collaborator. Can be one of:
#     # * `pull` - can pull, but not push to or administer this repository.
#     # * `push` - can pull and push, but not administer this repository.
#     # * `admin` - can pull, push and administer this repository.
#     permission: push

#   - username: hubot
#     permission: pull

#   - username:
#     permission: pull

# branches:
#   - name: master
#     protection:
#       # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
#       required_pull_request_reviews:
#         # The number of approvals required. (1-6)
#         required_approving_review_count: 1
#         dismiss_stale_reviews: false
#         dismissal_restrictions:
#           users: []
#           teams: []
#       # Required. Require status checks to pass before merging. Set to null to disable
#       required_status_checks:
#         # Required. Require branches to be up to date before merging.
#         strict: true
#         # Required. The list of status checks to require in order to merge into this branch
#         contexts: []
#       # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
#       enforce_admins: true
#       # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
#       restrictions:
#         users: []
#         teams: []
